/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   name.h                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: rabouzia <rabouzia@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/07/17 18:29:09 by rabouzia          #+#    #+#             */
/*   Updated: 2024/07/17 18:29:46 by rabouzia         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef NAME_H
#define NAME_H

#define P1 "Ibn Battuta"
#define P2 "Ibn Al-Khattab"
#define P3 "Ibn Omar"
#define P4 "Imam Malik"
#define P5 "Imam Bukhari"
#define P6 "Imam Muslim"
#define P7 "Imam Shafi3i"
#define P8 "Abou Houreyra"
#define P9 "Ibn Khaldoun"
#define P10 "Ibn Abbas"
#define P11 "Ibn Hazm"
#define P12 "Ibn Sina"
#define P13 "Al-Farabi"
#define P14 "Al-Ghazali"
#define P15 "Al-Khwarizmi"
#define P16 "Ibn Rushd"
#define P17 "Ibn Taymiyyah"
#define P18 "Ibn Qayyim"
#define P19 "Al-Biruni"
#define P20 "Ibn Kathir"
#define P21 "Al-Tabari"
#define P22 "Al-Maqrizi"
#define P23 "Ibn Hisham"
#define P24 "Al-Jahiz"
#define P25 "Ibn Ishaq"
#define P26 "Al-Masudi"
#define P27 "Ibn Jubayr"
#define P28 "Al-Muqaddasi"
#define P29 "Al-Idrisi"
#define P30 "Ibn Battah"
#define P31 "Ibn Fadlan"
#define P32 "Al-Razi"
#define P33 "Al-Kindi"
#define P34 "Al-Farghani"
#define P35 "Ibn Abi Usaibia"
#define P36 "Ibn al-Nafis"
#define P37 "Ibn al-Haytham"
#define P38 "Al-Hasan ibn al-Haytham"
#define P39 "Ibn Hazm"
#define P40 "Ibn Miskawayh"
#define P41 "Ibn Arabi"
#define P42 "Al-Farabi"
#define P43 "Ibn Hajar"
#define P44 "Al-Munawi"
#define P45 "Al-Qurtubi"
#define P46 "Ibn Battah"
#define P47 "Ibn Tufail"
#define P48 "Ibn Zuhr"
#define P49 "Ibn Mandour"
#define P50 "Ibn Bassam"
#define P51 "Ibn al-Athir"
#define P52 "Ibn al-Jawzi"
#define P53 "Ibn Duraid"
#define P54 "Ibn Wahshiyya"
#define P55 "Al-Mas'udi"
#define P56 "Ibn Munqidh"
#define P57 "Ibn al-Adim"
#define P58 "Ibn al-Faqih"
#define P59 "Al-Khwarizmi"
#define P60 "Al-Jahiz"
#define P61 "Ibn Abi Zayd"
#define P62 "Ibn Ziyad"
#define P63 "Ibn Abi Hatim"
#define P64 "Ibn Abi Shaybah"
#define P65 "Al-Mawardi"
#define P66 "Ibn al-Qayyim"
#define P67 "Ibn Rajab"
#define P68 "Ibn Sa'd"
#define P69 "Ibn Majah"
#define P70 "Al-Dhahabi"
#define P71 "Ibn Hisham"
#define P72 "Ibn Hazm"
#define P73 "Ibn Khallikan"
#define P74 "Al-Baghdadi"
#define P75 "Ibn Zayd"
#define P76 "Ibn Taghribirdi"
#define P77 "Ibn Abi Dunya"
#define P78 "Ibn Abi Hisham"
#define P79 "Ibn Abd Rabbih"
#define P80 "Ibn Hamdan"
#define P81 "Ibn Marwan"
#define P82 "Ibn Al-Wardi"
#define P83 "Ibn Lubb"
#define P84 "Ibn al-Awwam"
#define P85 "Ibn al-Ahdal"
#define P86 "Ibn Kammuna"
#define P87 "Ibn Abi Hajalah"
#define P88 "Ibn Wahb"
#define P89 "Ibn Abi Rumaylah"
#define P90 "Ibn Abi Sarh"
#define P91 "Ibn Abi al-Izz"
#define P92 "Ibn Abi Zayd al-Qayrawani"
#define P93 "Ibn Abi al-Dunya"
#define P94 "Ibn Abi Usaibia"
#define P95 "Ibn Abdul Barr"
#define P96 "Ibn Abdul Hakam"
#define P97 "Ibn Hammad"
#define P98 "Ibn Jama'ah"
#define P99 "Ibn Juzayy"
#define P100 "Ibn al-Muqaffa"

#endif 